spring.application.name=workforce-management

server.port=${SERVER_PORT}

management.endpoints.web.exposure.include=*


# create .env file and add the values 

# PostgreSQL Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA/Hibernate Props    :
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# JWT Configuration

# Secret key 
app.jwt-secret=${JWT_SECRET}

# Token expiration time in milliseconds 
app.jwt-expiration-milliseconds=${JWT_EXPIRATION}

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}




